version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_VjYIGhFWeH31@ep-jolly-sun-adajtjlm-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    depends_on:
      - db
  
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=climate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: